# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mission4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mission4

    pod 'RxSwift'
    pod 'RxCocoa'

  target 'Mission4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
