# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMPizza' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMPizza
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'RxSwift', '6.0.0-rc.1'
  pod 'RxCocoa', '6.0.0-rc.1'

  target 'MVVMPizzaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMPizzaUITests' do
    # Pods for testing
  end

end
