# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Subway' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Subway
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '6.0.0-rc.1'
  pod 'RxCocoa', '6.0.0-rc.1'
  target 'SubwayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SubwayUITests' do
    # Pods for testing
  end

end
