# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mission01-Denny' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mission01-Denny
  pod 'Alamofire', '4.9.1'
  pod 'Kingfisher'
  pod 'SnapKit'
end
