# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mission03' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mission03
pod 'RxSwift','~>5'

end
